scheduled_job:
  script:
    - echo "Running fetch"
    - date +%T
    - npm run go
  rules:
  variables:
    S3_END_POINT: "sgp1.digitaloceanspaces.com"
    S3_ACCESS_KEY: ""
    S3_SECRET_KEY: ""
    S3_BUCKET: "abcnewsdata"
    S3_DEST: "data-time-series-weather/"
    AURORA_ENDPOINT: https://aurora.abc.net`.au/
    AURORA_API_KEY: ""
